token: insert your telegram bot token here
users:
  - telegram_id: 810722109
    role: Cantor
sweater:
  supported_relations_kinds:
    - answers
    - negates
    - may be
    - means
    - therefore
    - includes
  chest:
    index:
      database:
        log:
          path: /tmp/chant/log.dat
        tables:
          object_id_and_path_to_value:
            index:
              path: /tmp/chant/tables/object_id_and_path_to_value/index.idx
            data_pool:
              variable:
                directory: /tmp/chant/tables/object_id_and_path_to_value/data
                max_element_size: 65536
          tag_and_object:
            index:
              path: /tmp/chant/tables/tag_and_object/index.idx
            data_pool:
              fixed:
                path: /tmp/chant/tables/tag_and_object/data.dat
                container_size: 32
          object_and_tag:
            index:
              path: /tmp/chant/tables/object_and_tag/index.idx
            data_pool:
              fixed:
                path: /tmp/chant/tables/object_and_tag/data.dat
                container_size: 32
          id_to_source:
            index:
              path: /tmp/chant/tables/id_to_source/index.idx
            data_pool:
              variable:
                directory: /tmp/chant/tables/id_to_source/data
                max_element_size: 65536
          tag_to_objects_count:
            index:
              path: /tmp/chant/tables/tag_to_objects_count/index.idx
            data_pool:
              fixed:
                path: /tmp/chant/tables/tag_to_objects_count/data.dat
                container_size: 20
          object_to_tags_count:
            index:
              path: /tmp/chant/tables/object_to_tags_count/index.idx
            data_pool:
              fixed:
                path: /tmp/chant/tables/object_to_tags_count/data.dat
                container_size: 20


